sudo: required
dist: trusty
language: cpp
compiler: gcc
before_script:
  - git clone --depth 1 https://github.com/felipetavares/bake
  - cd bake
  - make
  - sudo make install
  - cd ..
script:
  - cd blog
  - bake
  - bake feed
  - ls
